language: rust
sudo: 9000
dist: trusty
rust:
  - nightly
os:
  - linux
  - osx
env:
  - FEATURES=""
  - FEATURES="--features debugmozjs"

env:
  - FEATURES=""
  - FEATURES="debugmozjs"

script:
  - cargo build --verbose --features "$FEATURES"
  - cargo test --verbose --features "$FEATURES"

branches:
  except:
    - master
notifications:
  webhooks: http://build.servo.org:54856/travis

script: |
  travis_wait cargo build --verbose $FEATURES
  cargo test --verbose --features $FEATURES
  cargo run --example callback $FEATURES
