version: 1.0.{build}

environment:
  PATH: 'C:\msys64\mingw64\bin;C:\msys64\usr\bin\;%PATH%'
  MSYSTEM: 'MSYS'
  MSYS: 'winsymlinks=lnk'
  matrix:
  - TARGET: nightly-x86_64-pc-windows-msvc
  - TARGET: nightly-x86_64-pc-windows-gnu

install:
  - bash -lc "echo $MSYSTEM; pacman --needed --noconfirm -Sy pacman-mirrors"
  - bash -lc "pacman --noconfirm -Sy"
  - bash -lc "pacman -Sy --needed --noconfirm git mingw-w64-x86_64-toolchain tar make python2-setuptools"
  - bash -lc "easy_install-2.7 pip virtualenv"
  - bash -lc "mv /mingw64/bin/python2.exe /mingw64/bin/python2-mingw64.exe"
  - bash -lc "mv /mingw64/bin/python2.7.exe /mingw64/bin/python2.7-mingw64.exe"
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:TARGET}.exe" -FileName "rust-install.exe"
  - ps: .\rust-install.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - ps: $env:PATH="$env:PATH;C:\rust\bin"
  - rustc -vV
  - cargo -vV
build_script:
  - cmd: >-
      set MSYSTEM=MINGW64

      bash -lc "cd $APPVEYOR_BUILD_FOLDER; cargo build && cargo test"
